function y = yguessfun_continued(s,sfun,dsvs,vn,dsvn,mss,tns,dV,dX,vs,dsnew,I)
y = [dsvs(sfun(s));...
     vn(sfun(s));...
     dsvn(sfun(s));...
     mss(sfun(s));...
     tns(sfun(s));...
     dV(sfun(s));...
     dX(sfun(s));...
     vs(sfun(s));...
     dsnew(sfun(s));...
     I(sfun(s))];
end

