function V = volume_from_profile(s, X, Z)
% Volume of an axisymmetric surface generated by (X(s), Z(s))
dZds = gradient(Z, s);
V = pi * trapz(s, X.^2 .* dZds);
V = abs(V);  % ensure positive if orientation flips
end